# Generated by Django 5.1.4 on 2024-12-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restik', '0002_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('other', 'Інше'), ('hot_dishe', 'Гарячі страви'), ('non_alc_drink', 'Без акогольні напої'), ('long_alc_drink', 'Лонги'), ('short_alc_drink', 'Шоти'), ('salat', 'Салати'), ('side_dish', 'Гарніри')], default='other', max_length=255, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.IntegerField(blank=True, verbose_name='Вага'),
        ),
    ]
